export const VOLUME_CHANGE_DIRECTIONS = {
    DOWN: 0x00,
    UP: 0x01
} as const;

export type VOLUME_CHANGE_DIRECTION = typeof VOLUME_CHANGE_DIRECTIONS[keyof typeof VOLUME_CHANGE_DIRECTIONS];

export const MULTI_FUNCTION_STEERING_WHEEL_BUTTONS = {
    NEXT_REL: 0x21,
    PREV_REL: 0x28,
    RT_PRESS: 0x40,
    RT_REL: 0x00,
    VOICE_PRESS: 0x80,
    VOICE_HOLD: 0x90,
    VOICE_REL: 0xA0
} as const;

export type MULTI_FUNCTION_STEERING_WHEEL_BUTTON = typeof MULTI_FUNCTION_STEERING_WHEEL_BUTTONS[keyof typeof MULTI_FUNCTION_STEERING_WHEEL_BUTTONS];

export const MULTI_FUNCTION_STEERING_WHEEL_COMMANDS = {
    BUTTON_PRESS: 0x3B,
    VOLUME_BUTTON_PRESS: 0x32
}

export type MULTI_FUNCTION_STEERING_WHEEL_COMMAND = typeof MULTI_FUNCTION_STEERING_WHEEL_COMMANDS[keyof typeof MULTI_FUNCTION_STEERING_WHEEL_COMMANDS];
