export const KNOWN_DEVICES = {
    DMEK: 0xB8,
    DME: 0x12,
    EGS: 0x32,
    EHC: 0xAC,
    EKM: 0x02,
    EKP: 0x65,
    FHK: 0xA7,
    HAC: 0x9A,
    HKM: 0x0F,
    NAVC: 0xA8,
    CVM: 0x52,
    PIC: 0xF1,
    RCSC: 0x81,
    SES: 0xB0,
    GR: 0xA6,
    ASC: 0x56,
    CSU: 0xF5,
    ABG: 0xA4,
    AHL: 0x66,
    GM: 0x00,
    SHD: 0x08,
    CDC: 0x18,
    RCC: 0x28,
    CCM: 0x30,
    GT: 0x3B,
    GTF: 0x43,
    DIA: 0x3F,
    LWS: 0x57,
    FBZV: 0x40,
    EWS: 0x44,
    CID: 0x46,
    MFL: 0x50,
    MML: 0x51,
    IHKA: 0x5B,
    PDC: 0x60,
    RAD: 0x68,
    DSP: 0x6A,
    DSPC: 0xEA,
    SM: 0x72,
    SDRS: 0x73,
    CDCD: 0x76,
    NAVE: 0x7F,
    IKE: 0x80,
    MMR: 0x9B,
    MM3: 0x9C,
    FID: 0xA0,
    NAVJ: 0xBB,
    GLO: 0xBF,
    MID: 0xC0,
    TEL: 0xC8,
    ASST: 0xCA,
    LCM: 0xD0,
    IRIS: 0xE0,
    RDC: 0x70,
    ANZV: 0xE7,
    RLS: 0xE8,
    VID: 0xED,
    SOR: 0x74,
    BMBT: 0xF0,
    FMBT: 0x47,
    TCU: 0xCA,
    STH: 0x6B,
    LOC: 0xFF,
    SMAD: 0xDA
} as const;

export type KNOWN_DEVICE = typeof KNOWN_DEVICES[keyof typeof KNOWN_DEVICES];

export type DEVICE = KNOWN_DEVICE | number;

export type DEVICE_SHORT_NAME = keyof typeof KNOWN_DEVICES;

export const KNOWN_DEVICE_NAMES: Record<DEVICE_SHORT_NAME, string> = {
    ABG: "Airbag",
    AHL: "Adaptive headlight unit",
    ANZV: "Display group",
    ASC: "Anti-lock braking system with ASC",
    ASST: "BMW Assist",
    BMBT: "On board monitor control panel",
    CCM: "Check control messages",
    CDC: "CD changer",
    CDCD: "CD changer (DIN size)",
    CID: "Center information display",
    CSU: "Centre switch control unit",
    CVM: "Cabrio folding top module",
    DIA: "Diagnostic",
    DME: "Digital Motor Electronics",
    DMEK: "DME (K2000 protocol)",
    DSP: "Digital sound processor amplifier",
    DSPC: "Digital sound processor controller",
    EGS: "Electronic gearbox control",
    EHC: "Electronic height control",
    EKM: "Electronic body module",
    EKP: "Electronic fuel pump",
    EWS: "EWS immobilizer",
    FBZV: "Key fob (only older E38)",
    FHK: "Automatic climate control, rear",
    FID: "Multi-information display, rear",
    FMBT: "Rear monitor controls",
    GLO: "Global",
    GM: "General module",
    GR: "Cruise control",
    GT: "Navigation",
    GTF: "Navigation, rear",
    HAC: "Headlight aim control",
    HKM: "Boot lid control unit",
    IHKA: "Automatic climate control",
    IKE: "Cluster",
    IRIS: "Integrated radio information system",
    LCM: "Light/check module",
    LOC: "Local",
    LWS: "Steering angle sensor",
    MFL: "Multi function lever",
    MID: "Multi-information display",
    MM3: "Mirror memory 3",
    MML: "Mirror memory, left",
    MMR: "Mirror memory, right",
    NAVC: "Navigation China",
    NAVE: "Navigation Europe",
    NAVJ: "Navigation Japan",
    PDC: "Park distance control",
    PIC: "Programmable controller (custom unit)",
    RAD: "Radio",
    RCC: "Radio controlled clock",
    RCSC: "Revolution counter/steering column",
    RDC: "Tire pressure control",
    RLS: "Rain/light sensor",
    SDRS: "Sirius sat radio",
    SES: "Handfree/speech input",
    SHD: "Sunroof module",
    SM: "Seat memory",
    SMAD: "Seat memory assistant driver",
    SOR: "Seat occupancy recognition unit",
    STH: "Standing heat",
    TCU: "Telematics control unit",
    TEL: "Telephone",
    VID: "Video input/TV tuner",
} as const;