export const KNOWN_DEVICES = {
    BODY_MODULE: 0x00,
    "SunroofControl": 0x08,
    CD_CHANGER: 0x18,
    "RadioControlledClock": 0x28,
    "CheckControlModule": 0x30,
    "GraphicsNavigationDriver": 0x3B,
    DIAGNOSTIC: 0x3F,
    "RemoteControlCentralLocking": 0x40,
    "GraphicsDriverRearScreen": 0x43,
    "Immobiliser": 0x44,
    "CentralInformationDisplay": 0x46,
    "MultiFunctionSteeringWheel": 0x50,
    "MirrorMemory": 0x51,
    "IntegratedHeatingAndAirConditioning": 0x5B,
    "ParkDistanceControl": 0x60,
    RADIO: 0x68,
    "DigitalSignalProcessingAudioAmplifier": 0x6A,
    "SeatMemory": 0x72,
    "SiriusRadio": 0x73,
    CD_CHANGER_DIN: 0x76,
    "NavigationEurope": 0x7F,
    "InstrumentClusterElectronics": 0x80,
    "MirrorMemorySecond": 0x9B,
    "MirrorMemoryThird": 0x9C,
    "RearMultiInfoDisplay": 0xA0,
    "AirBagModule": 0xA4,
    "SpeedRecognitionSystem": 0xB0,
    "NavigationJapan": 0xBB,
    GLOBAL_BROADCAST: 0xBF,
    "MultiInfoDisplay": 0xC0,
    "Telephone": 0xC8,
    "Assist": 0xCA,
    LIGHT_CONTROL_MODULE: 0xD0,
    "SeatMemorySecond": 0xDA,
    "IntegratedRadioInformationSystem": 0xE0,
    DISPLAYS_MULTICAST: 0xE7,
    RAIN_LIGHT_SENSOR: 0xE8,
    "Television": 0xED,
    "OnBoardMonitor": 0xF0,
    BROADCAST: 0xFF
} as const;

export type KNOWN_DEVICE = typeof KNOWN_DEVICES[keyof typeof KNOWN_DEVICES];

export type DEVICE = KNOWN_DEVICE | number;