export const RADIO_COMMANDS = {
    /*
    #define IBUS_CMD_RAD_LED_TAPE_CTRL 0x4A

#define IBUS_CMD_RAD_SCREEN_MODE_UPDATE 0x46
#define IBUS_CMD_RAD_UPDATE_MAIN_AREA 0x23
#define IBUS_CMD_RAD_C43_SCREEN_UPDATE 0x21
#define IBUS_CMD_RAD_C43_SET_MENU_MODE 0xC0
#define IBUS_CMD_RAD_WRITE_MID_DISPLAY 0x23
#define IBUS_CMD_RAD_WRITE_MID_MENU 0x21
*/
} as const;

export type RADIO_COMMAND = typeof RADIO_COMMANDS[keyof typeof RADIO_COMMANDS];

export const CD53_DISPLAY_TEXT_LENGTH = 11;
export const BLANK_CHAR = 0x9D;